### ISSUE TITLE
Ability to configure OpsQueueFactories

### ISSUE THREAD

**Issue by incubos** [alexandru/shade#10]
It is impossible to pass custom (bounded) `OpsQueueFactory`s, because `MemcachedImpl` just uses default `ConnectionFactoryBuilder` settings when constructing `instance`. It leads to possible unbounded heap growth when network flaps are happening.

**Comment by lloydmeta** [comment]
A PR was issued a while back for this https://github.com/alexandru/shade/pull/4/files

**Comment by lloydmeta** [comment]
Closing since #4 has been merged and the ops queue is now configurable
