### ISSUE TITLE
"Supported for Scala versions: 2.10.x, to be updated for 2.11 as soon as it's final."

### ISSUE THREAD

**Issue by q42jaap** [alexandru/shade#12]
Is there still progress on the 2.11 build???

**Comment by lloydmeta** [comment]
1.7.1 has a 2.11 build so perhaps this is just an issue with the readme.

**Comment by alexandru** [comment]
Yes guys, 2.11 is already supported, the README needs an update.

**Comment by lloydmeta** [comment]
Just updated the Readme; closing this now.
