### ISSUE TITLE
It's been 2 years--please remove the SNAPSHOT

### ISSUE THREAD

**Issue by gzoller** [alexandru/shade#13]
Unless there's outstanding issues needing fixing, please remove SNAPSHOT and release 1.7.0.

The SNAPSHOT forces sbt to re-resolve every time, which is causing problems because I'm behind a corporate proxy.

Great library--thanks!

**Comment by alexandru** [comment]
Sorry for the inconvenience @gzoller, I will. Please standby.

**Comment by lloydmeta** [comment]
:+1:

**Comment by gzoller** [comment]
Super cool, thanks!  Nice library.

**Comment by gzoller** [comment]
Bump.  Please make final. :-)

**Comment by lloydmeta** [comment]
@alexandru released 1.7.1 this morning, so this can now be closed.
