### ISSUE TITLE
Update SpyMemcached dependency to latest version - 2.11.1

### ISSUE THREAD

**Issue by alexandru** [alexandru/shade#2]
Scheduled for next release - 1.7.0

**Comment by zfy0701** [comment]
is there any update on this?

**Comment by jknight12882** [comment]
following up on this, as Scala has reached a mature 2.11.4 status

**Comment by alexandru** [comment]
Sorry guys for waiting - GitHub for some reason stopped sending me notifications on issues opened, I will update it as soon as possible - meaning sometimes this week.

**Comment by lloydmeta** [comment]
:+1:

Great lib just bumping

**Comment by lloydmeta** [comment]
The latest 1.7.1 release of Shade uses SpyMemcached 2.11.7, so this can now be closed as well
