### ISSUE TITLE
Rewrite history of repository to change email

### ISSUE THREAD

**Issue by alexandru** [alexandru/shade#28]
@lloydmeta @zaneli,

I am rewriting the history of shade to change all my emails to `noreply@alexn.org`. And this is because GitHub has become a spam problem for me and I don't want to expose my real emails anymore.

What I did was to basically follow this tutorial:
https://help.github.com/articles/changing-author-info/

If you have forks in progress, you'll have to rebase with the new master.
Sorry for the inconvenience.

**Comment by alexandru** [comment]
Btw, now that I force pushed, I have enabled branch protection, as a reminder that we shouldn't do this :)

**Comment by lloydmeta** [comment]
I see no worries I don't have any open forks.

**Comment by alexandru** [comment]
In any case, here's a recipe for dealing with it:

1. DO NOT do a `git pull`
2. `git fetch`
3. `git rebase --onto origin/master master <local_branch>` (for local each branch)
4. `git pull --force`

**Comment by lloydmeta** [comment]
@alexandru thanks that helped. #29 went through successfully so I guess I followed your instructions correctly :wink:

**Comment by zaneli** [comment]
I don't have fork in progress, too.
Thank you for inform.
