### ISSUE TITLE
Replace Monifu with Sincron in dependencies

### ISSUE THREAD

**Issue by alexandru** [alexandru/shade#33]
Shade has `"org.monifu" %% "monifu-core" % "1.0"` in its dependencies. It does so because of its atomic references implementation. 

It will have to be replaced with [project Sincron](https://github.com/monixio/sincron), for one because going forward that's where the atomic references will be, but also because the `Atomic.transform` methods were replaced with macros that bypass the inlining problem and will make dependent code much more efficient (e.g. the in-memory cache).

And because we care about performance enough to make this update, we should also introduce benchmarks by means of JMH (sbt-jmh).

I'm postponing the update for now because I have to make sure that Sincron is stable, but if we schedule a new version of Shade in 2 months, then that's about right.

**Comment by lloydmeta** [comment]
Sounds like a great idea. I'll schedule this in for 1.7.3 in 2 months.
